### ISSUE TITLE
https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.zh-cn/blob/main/Instructions/Exercises/M04-Unit%204%20Create%20and%20configure%20an%20Azure%20load%20balancer.md --Broken Graphic

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.zh-cn#1]
# Module: 04
#### Step: 00

Description of issue

There is a broken graphic here:

![image](https://user-images.githubusercontent.com/49700217/177643378-bf5dc49d-b3ec-4dc1-9796-1457b9f59d26.png)

This link points to (../media/create-load-balancer-4.png) but this .png file does not exist in that dir.

**Comment by stonezy123** [comment]
Show image. Fixed.
Need to select OLPRODLOC branch to check, not Main branch.

![image](https://user-images.githubusercontent.com/49666210/185027159-456bf994-25b9-433e-b0b6-b98e293a2e3c.png)


https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.zh-cn/blob/OLPRODLOC/Instructions/Exercises/M04-Unit%204%20Create%20and%20configure%20an%20Azure%20load%20balancer.md
