### ISSUE TITLE
https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.zh-cn/blob/main/Instructions/Exercises/M08-Unit%203%20Monitor%20a%20load%20balancer%20resource%20using%20Azure%20Monitor.md -- Broken Graphic

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.zh-cn#2]
# Module: 08
#### Step: 00

Description of issue

There is a broken graphic here:
![image](https://user-images.githubusercontent.com/49700217/177645939-a5bad20d-8bc6-4af6-8989-981a9f422acd.png)

This link points to (../media/create-load-balancer-4.png) but this .png file does not exist in that dir.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Show image. Fixed.
Need to select OLPRODLOC branch to check.
https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.zh-cn/blob/OLPRODLOC/Instructions/Exercises/M08-Unit%203%20Monitor%20a%20load%20balancer%20resource%20using%20Azure%20Monitor.md

![image](https://user-images.githubusercontent.com/49666210/185025637-7e73546f-8f6a-4a7f-a902-aafc08ddfdab.png)
