### ISSUE TITLE
M03-Unit 5 Provision an ExpressRoute circuit.md: ENG version updates being translated soon?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.zh-cn#3]
This set of instructions has had an update in the ENG version, hopefully it will soon be translated and updated here?  Note that with this change it is important to have an updated screenshot showing the new settings.  I am including a reference to the ENG version highlighting the important changes:

![image](https://user-images.githubusercontent.com/49700217/203122735-c6400aa0-bad3-4f21-9327-8720814e03a1.png)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Manually added the file and its displaying
