### ISSUE TITLE
M07-Unit 5 Restrict network access to PaaS resources with virtual network service endpoints - issues with screenshots

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.zh-cn#4]
I am cross-posting this issue from the ja-jp repo, since it appears the same issue(s) with screenshots exist here as well:

https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ja-jp/issues/3

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
zh-cn is like en-us here
Tagging for the WWL team to review but closing
